config/routes.rb
Rails.application.routes.draw do
  devise_for :tourmen, controllers: {
    sessions: 'tourman/sessions',
    registrations: 'tourman/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get '/pages/search', to: 'pages#search'
  root to: 'pages#home'
  get  'pages/user_dashboard'
  get 'pages/user_concert_dashboard'
  get 'pages/tourman'

  get 'pdf_generator/generate_pdf/:id', to: 'pdf_generator#generate_pdf', as: 'generate_pdf'

  resources :venues
  resources :hotels
  resources :checklist_templates, only: [:new, :create]
  resources :concert_templates, only: [:new, :create, :show] do
    member do
      post 'update_notes', action: :update_notes, as: 'update_notes'
      post 'new_note', action: :new_note, as: 'new_note'
      post 'delete_note', action: :delete_note, as: 'delete_note'
      post 'update_timetable', action: :update_timetable, as: 'update_timetable'
      post 'update_checkbox', action: :update_checkbox, as: 'update_checkbox'
      post 'new_checkbox', action: :new_checkbox, as: 'new_checkbox'
      post 'delete_checkbox', action: :delete_checkbox, as: 'delete_checkbox'
      post 'new_timetable', action: :new_timetable, as: 'new_timetable'
      post 'delete_timetable', action: :delete_timetable, as: 'delete_timetable'
      post 'new_transport', action: :new_transport, as: "new_transport"
      post 'update_transport', action: :update_transport, as: "update_transport"
      post 'delete_transport', action: :delete_transport, as: "delete_transport"
      post 'update_name', action: :update_name, as: "update_name"
      post 'delete_template', action: :delete_template, as: "delete_template"
      post 'update_hotel', action: :update_hotel, as: "update_hotel"
      post 'delete_hotel', action: :delete_hotel, as: "delete_hotel"
      post 'new_hotel', action: :new_hotel, as: "new_hotel"
      post 'create_from_template', action: :create_from_template, as: 'create_from_template'
    end
  end

  resources :tours do
    resources :concerts, except: [:index] do
      resources :timetable_entries, only: [:create, :destroy, :update]
      resources :contacts, only: [:create, :destroy, :update]
      resources :guest_lists, only: [:create, :destroy]
      resources :transports, only: [:create, :destroy, :update] do
        resources :transport_users, only: [:create, :update, :destroy] do
          member do
            delete 'destroy_attachment/:attachment_id', action: :destroy_attachment, as: :destroy_attachment
          end
        end
      end
      resources :crew_user_concerts, only: [:create, :destroy]
      resources :guests, only: [:create, :destroy, :update]
      resources :notes, only: [:create, :destroy, :update]
      resources :checklists, only: [:create, :destroy, :update] do
        collection do
          get 'import'
        end
      end
      delete 'removetimetable/:timetable_entry_id', action: :removetimetable, as: 'removetimetable'
      delete 'remove_contact/:contact_id', action: :remove_contact, as: 'remove_contact'
      patch :remove_venue, on: :member
      patch :remove_hotel, on: :member
      resources :concert_hotels, only: [:create, :destroy] do
        member do
          delete 'remove_user/:user_id', action: :remove_user, as: 'remove_user'
          delete 'remove_guest/:guest_id', action: :remove_guest, as: 'remove_guest'
          post 'add_crew', action: :add_crew, as: 'add_crew'
          post 'add_guest', action: :add_guest, as: 'add_guest'
        end
      end

      get 'roadbook_email', action: :roadbook_email, as: "roadbook_email"

    end
  end

  resources :crews do
    member do
      post 'assign_users'
      put 'assign_users_role'
      put 'update_role_in_crew_member/:user_id', to: 'crews#update_role_in_crew_member', as: :update_role_in_crew_member
      delete 'unassign_user/:user_id', action: :unassign_user, as: :unassign_user
    end
  end

end

app/models/crew.rb
class Crew < ApplicationRecord
  has_many :crew_users
  has_many :users, through: :crew_users, dependent: :destroy
  has_one :tour, dependent: :destroy
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: [:show, :assign_users, :assign_users_role, :update_role_in_crew_member, :unassign_user]
  before_action :set_tours_and_concert_templates, only: [:show]

  def show
    @users = User.all
    @crew_users = CrewUser.where(crew_id: @crew).order(created_at: :asc)
    @tour = Tour.find_by(crew_id: @crew.id)
  end

  def assign_users
    service = CrewCreationService.new(params[:user_ids], @crew)
    service.call
    if service.success
      redirect_to @crew, notice: "#{service.user} were successfully assigned"
    else
      redirect_to @crew, notice: 'Something went wrong'
    end
  end

  def assign_users_role
    @crewuser = CrewUser.find_by(user_id: params[:format], crew_id: params[:id] )
    role = params[:role]
    if @crewuser.update(role: role)
      render json: { success: true, role: @crewuser.role }
    else
      render json: { success: false, errors: @crewuser.errors.full_messages }
    end
  end

  def update_role_in_crew_member
    @crewuser = CrewUser.find_by(user_id: params[:user_id], crew_id: params[:id] )
    @crewuser.role = nil
    if @crewuser.save
      render json: { success: true, role: @crewuser.role }
    else
      render json: { success: false, errors: @crewuser.errors.full_messages }
    end
  end

  def unassign_user
    @crew_user = CrewUser.find(params[:user_id])
    if @crew_user.destroy
      redirect_to @crew, notice: 'User was successfully unassigned from the team.'
    else
      redirect_to @crew, notice: "Couldn't destroy this user."
    end
  end

  private

  def set_crew
    @crew = Crew.find_by(id: params[:id])
    if @crew.present?
      authorize @crew
    else
      redirect_to tours_path, notice: "Something went wrong"
    end
  end

  def set_tours_and_concert_templates
    @tours = Tour.where(tourman_id: current_tourman.id)
    @concert_templates = ConcertTemplate.where(tourman_id: current_tourman.id)
  end
end

app/views/crews/show.html.erb
<div class="body-container crew-container">
  <div data-controller="crew">
    <div class="d-flex align-items-center mb-3">
      <h1 class="me-3"><%= @crew.name.upcase %></h1>
    </div>
    <div class="row justify-content-between">
      <div class="col-lg-4  me-3 mb-3">
        <div class="container-white">
          <h2>SEARCH</h2>
          <%= form_tag(assign_users_crew_path(@crew), method: :post) do %>
            <div>
              <input data-crew-target="searchInput" type="text" id="crew-search" placeholder="Search crew" data-action="input->crew#search" class="form-input">
              <div data-crew-target="results"></div>
              <%= select_tag "user_ids[]", options_for_select(@users.map {
                |user| [ "#{user.first_name} #{user.last_name} #{image_tag(user.image, alt: user.full_name) if user.image.attached?}", user.id]
                },
                params[:user_ids]),
                multiple: true,
                data: { crew_target: "selectUsers" },
                class: "d-none result-crew-search" %>
            </div>
            <%= submit_tag "ADD TO CREW",  class: "button-green mt-3"%>
          <% end %>
        </div>
      </div>
      <div class="col-lg-7">
        <div class="container-white">
          <div class="box-shadow-bottom d-flex align-items-center justify-content-between">
            <h2>CREW MEMBERS</h2>
            <p class="m-0">Assign a role</>
          </div>
          <div class="listtoggle">
            <ul class="list-unstyled list-crew-users-phones">
              <% @crew_users.each_with_index do |crew_user, index|%>
                  <% member = User.find(crew_user[:user_id]) %>
                  <li>
                    <div class="list-crew-members d-flex justify-content-between align-items-center">
                      <div class="d-flex align-items-center">
                          <%= link_to raw('<i class="fas fa-times-circle green-cross-delete me-3"></i>'), unassign_user_crew_path(@crew, crew_user), data: { turbo_method: :delete,  turbo_confirm: 'Are you sure?' } %>
                          <div>
                            <%= image_tag(member.image, class: "avatar me-3") if member.image.attached? %>
                            <% unless member.image.attached? %>
                              <%= image_tag "profile.png", class: "avatar me-3" %>
                            <% end %>
                          </div>
                          <div><p><%= crew_user.user.first_name %> <%= crew_user.user.last_name %></p></div>
                      </div>
                      <div class="crew-role-delete d-flex align-items-center">

                          <div class="d-flex align-items-center me-3">
                            <strong data-crew-target="crewuserrole<%= index %>"><p><%= crew_user.role %></p></strong>
                          </div>
                          <div class="margin-bot-seven d-flex align-items-center" data-crew-target="divplusorminus<%= index %>">
                            <% if crew_user.role.nil? %>
                              <a href="#" data-action="click->crew#openModal"  data-index="<%= index %>"><i class="fas fa-plus open-plus-icon"></i></a>
                            <% else %>
                              <%= link_to raw('<i class="fa-solid fa-minus open-plus-icon"></i>'), "#", data: {action: "click->crew#updateRole", url: url_for(update_role_in_crew_member_crew_path(@crew, crew_user.user_id)), index: index,  confirmMessage: "Are you sure?" } %>
                            <% end %>
                          </div>
                          <div data-crew-target="role<%= index %>" class="d-none" data-index="<%= index %>" >
                            <%= form_tag(assign_users_role_crew_path(@crew, crew_user.user_id), method: :put, data: { crew_target: "form#{index}" }) do %>
                              <div class="d-flex align-items-center">
                                <%= text_field_tag "role", nil, placeholder: "Role in team", class: "form-input-black-short me-3" %>
                                <%= submit_tag "NEW ROLE", class: "button-green", data: { action: "click->crew#closeModal", index: index, crew_target: "submit#{index}"  } %>
                              </div>
                            <% end %>
                          </div>

                      </div>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-white mt-3">
    <p class="m-0">
      <i class="fa-solid fa-circle-info me-3"></i>
      Your Crew refers to the main team of the show, it will be automatically be assigned to all your shows.
    </p>
  </div>
</div>