config/routes.rb
Rails.application.routes.draw do
  devise_for :tourmen, controllers: {
    sessions: 'tourman/sessions',
    registrations: 'tourman/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get '/pages/search', to: 'pages#search'
  root to: 'pages#home'
  get  'pages/user_dashboard'
  get 'pages/user_concert_dashboard'
  get 'pages/tourman'

  get 'pdf_generator/generate_pdf/:id', to: 'pdf_generator#generate_pdf', as: 'generate_pdf'

  resources :venues
  resources :hotels
  resources :checklist_templates, only: [:new, :create]
  resources :concert_templates, only: [:new, :create, :show] do
    member do
      post 'update_notes', action: :update_notes, as: 'update_notes'
      post 'new_note', action: :new_note, as: 'new_note'
      post 'delete_note', action: :delete_note, as: 'delete_note'
      post 'update_timetable', action: :update_timetable, as: 'update_timetable'
      post 'update_checkbox', action: :update_checkbox, as: 'update_checkbox'
      post 'new_checkbox', action: :new_checkbox, as: 'new_checkbox'
      post 'delete_checkbox', action: :delete_checkbox, as: 'delete_checkbox'
      post 'new_timetable', action: :new_timetable, as: 'new_timetable'
      post 'delete_timetable', action: :delete_timetable, as: 'delete_timetable'
      post 'new_transport', action: :new_transport, as: "new_transport"
      post 'update_transport', action: :update_transport, as: "update_transport"
      post 'delete_transport', action: :delete_transport, as: "delete_transport"
      post 'update_name', action: :update_name, as: "update_name"
      post 'delete_template', action: :delete_template, as: "delete_template"
      post 'update_hotel', action: :update_hotel, as: "update_hotel"
      post 'delete_hotel', action: :delete_hotel, as: "delete_hotel"
      post 'new_hotel', action: :new_hotel, as: "new_hotel"
      post 'create_from_template', action: :create_from_template, as: 'create_from_template'
    end
  end

  resources :tours do
    resources :concerts, except: [:index] do
      resources :timetable_entries, only: [:create, :destroy, :update]
      resources :contacts, only: [:create, :destroy, :update]
      resources :guest_lists, only: [:create, :destroy]
      resources :transports, only: [:create, :destroy, :update] do
        resources :transport_users, only: [:create, :update, :destroy] do
          member do
            delete 'destroy_attachment/:attachment_id', action: :destroy_attachment, as: :destroy_attachment
          end
        end
      end
      resources :crew_user_concerts, only: [:create, :destroy]
      resources :guests, only: [:create, :destroy, :update]
      resources :notes, only: [:create, :destroy, :update]
      resources :checklists, only: [:create, :destroy, :update] do
        collection do
          get 'import'
        end
      end
      delete 'removetimetable/:timetable_entry_id', action: :removetimetable, as: 'removetimetable'
      delete 'remove_contact/:contact_id', action: :remove_contact, as: 'remove_contact'
      patch :remove_venue, on: :member
      patch :remove_hotel, on: :member
      resources :concert_hotels, only: [:create, :destroy] do
        member do
          delete 'remove_user/:user_id', action: :remove_user, as: 'remove_user'
          delete 'remove_guest/:guest_id', action: :remove_guest, as: 'remove_guest'
          post 'add_crew', action: :add_crew, as: 'add_crew'
          post 'add_guest', action: :add_guest, as: 'add_guest'
        end
      end

      get 'roadbook_email', action: :roadbook_email, as: "roadbook_email"

    end
  end

  resources :crews do
    member do
      post 'assign_users'
      put 'assign_users_role'
      put 'update_role_in_crew_member/:user_id', to: 'crews#update_role_in_crew_member', as: :update_role_in_crew_member
      delete 'unassign_user/:user_id', action: :unassign_user, as: :unassign_user
    end
  end

end

app/models/concert_template.rb
class ConcertTemplate < ApplicationRecord
  serialize :data, JSON
end

app/controllers/concert_templates_controller.rb
class ConcertTemplatesController < ApplicationController
  def new
    if params[:format] != nil
      concert = Concert.find(params[:format].to_i)
      data = {
        concert: concert.attributes,
        checklists: concert.checklists.map(&:attributes),
        contacts: concert.contacts.map(&:attributes),
        hotels: concert.hotels.map(&:attributes),
        notes: concert.notes.map(&:attributes),
        timetable_entries: concert.timetable_entries.map(&:attributes),
        transports: concert.transports.map(&:attributes),
      }
      @concert_template = ConcertTemplate.new(data: data.to_json, name: params[:template_name])
      @concert_template.tourman_id = current_tourman.id
      authorize  @concert_template
      @concert_template.save
      redirect_to concert_template_path(@concert_template), notice: 'Template created'
    else
      concert = Concert.new
      data = {
        concert: concert.attributes,
        checklists: concert.checklists.map(&:attributes),
        contacts: concert.contacts.map(&:attributes),
        hotels: concert.hotels.map(&:attributes),
        notes: concert.notes.map(&:attributes),
        timetable_entries: concert.timetable_entries.map(&:attributes),
        transports: concert.transports.map(&:attributes),
      }
      @concert_template = ConcertTemplate.new(data: data.to_json, name: "New Template")
      @concert_template.tourman_id = current_tourman.id
      @concert_template.save
      authorize  @concert_template
      redirect_to concert_template_path(@concert_template), notice: 'Template created'
    end
  end

  def create
  end

  def show
    @concert_templates = ConcertTemplate.where(tourman_id: current_tourman.id)
    @tours = Tour.where(tourman_id: current_tourman.id)
    @phoneprefix = ISO3166::Country.all.map { |country| "#{country.country_code}" }
    @phoneprefixsorted = @phoneprefix.uniq.sort_by(&:to_i).map {|c| "+#{c}"}
    @concert_template = ConcertTemplate.find(params[:id])
    authorize  @concert_template
    data = JSON.parse(@concert_template.data)
    @contacts_data = data['contacts']
    @timetable_entries_data = data['timetable_entries']&.sort_by! { |entry| entry['hourminute'] }
    @hotels_data = data['hotels']
    @transports_data = data['transports']
    @notes_data = data['notes']
    @checklists_data = data['checklists']
  end

  def update_notes
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["notes"][params[:index].to_i]["description"] = params[:note_description]
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def new_note
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["notes"] << {"description"=>params[:note_description]}
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def delete_note
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["notes"].delete_at(params[:index].to_i)
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def update_timetable
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["timetable_entries"][params[:index].to_i]["information"] = params[:entry]
    data["timetable_entries"][params[:index].to_i]["hourminute"] = params[:start].to_time
    data["timetable_entries"][params[:index].to_i]["hourminuteend"] = params[:end].to_time
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Timetable updated'
  end

  def new_timetable
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["timetable_entries"] << {"information"=>params[:entry], "hourminute"=>params[:start].to_time,"hourminuteend"=>params[:end].to_time }
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def delete_timetable
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    @timetable_entries_data = data['timetable_entries']&.sort_by! { |entry| entry['hourminute'] }
    @timetable_entries_data.delete_at(params[:index].to_i)
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def update_checkbox
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["checklists"][params[:index].to_i]["description"] = params[:checkbox_description]
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def delete_checkbox
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["checklists"].delete_at(params[:index].to_i)
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def new_checkbox
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["checklists"] << {"description"=>params[:note_description]}
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def new_transport
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["transports"] << {"place_of_depart"=>params[:depart_place], "place_of_arrival"=>params[:arrival_place], "time_of_depart"=>params[:depart_time].to_time, "time_of_arrival"=>params[:arrival_time].to_time, "way_of_transport"=>params[:way_of_transport] }
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Transport Added'
  end

  def update_name
    @concert_template = ConcertTemplate.find(params[:id])
    @concert_template.name = params[:name]
    authorize  @concert_template
    @concert_template.save
    redirect_to concert_template_path(@concert_template), notice: 'Name Updated'
  end

  def update_transport
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["transports"][params[:index].to_i]["place_of_depart"] = params[:place_depart]
    data["transports"][params[:index].to_i]["place_of_arrival"] = params[:place_arrival]
    data["transports"][params[:index].to_i]["time_of_depart"] = params[:time_depart].to_time
    data["transports"][params[:index].to_i]["time_of_arrival"] = params[:time_arrival].to_time
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Transport updated'
  end

  def delete_transport
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["transports"].delete_at(params[:index].to_i)
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Template updated'
  end

  def delete_template
    @concert_template = ConcertTemplate.find(params[:id])
    authorize  @concert_template
    @concert_template.delete
    redirect_to tours_path, notice: 'Template Delete'
  end

  def update_hotel
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["hotels"][params[:index].to_i]["name"] = params[:hotel_name]
    data["hotels"][params[:index].to_i]["address"] = params[:hotel_address]
    data["hotels"][params[:index].to_i]["postcode"] = params[:hotel_postcode]
    data["hotels"][params[:index].to_i]["city"] = params[:hotel_city]
    data["hotels"][params[:index].to_i]["standing"] = params[:standing]
    data["hotels"][params[:index].to_i]["country"] = params[:hotel_country]
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Hotel Updated'
  end

  def delete_hotel
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["hotels"].delete_at(params[:index].to_i)
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Hotel Delete'
  end

  def new_hotel
    @concert_template = ConcertTemplate.find(params[:id])
    data = JSON.parse(@concert_template.data)
    data["hotels"] << {"name"=>params[:hotel_name], "address"=>params[:hotel_address], "city"=>params[:hotel_city], "postcode"=>params[:hotel_postcode], "country"=>params[:hotel_country], "standing"=>params[:standing]}
    authorize  @concert_template
    @concert_template.update(data: data.to_json)
    redirect_to concert_template_path(@concert_template), notice: 'Hotel Added'
  end

  def create_from_template
    @concert_template = ConcertTemplate.find(params[:id])
    authorize  @concert_template
    tour= Tour.find(params[:tour].to_i)
    data = JSON.parse(@concert_template.data)
    new_concert = Concert.new(tour_id: params[:tour].to_i, name: params[:venue], location: params[:city], date: params[:date].to_date)

app/views/concert_templates/_checkboxes.html.erb
<div class="col-12 container-white mt-2">
  <h2>CHECKBOXES (<%= @concert_template.name.upcase %>)</h2>
    <% @checklists_data.each_with_index do |checklist_data, index| %>
      <div class="d-flex align-items-center form-checklist-div justify-content-between mb-1">
        <div class="col-lg-6 d-flex align-items-center">
          <i class="fa-regular fa-square-check me-3"></i>
          <p class="m-0"><%= checklist_data["description"] %></p>
        </div>
        <div class="d-flex align-items-center col-lg-6 form-checklist-div-edit">
          <input data-concert-template-target="checkboxDescription<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateCheckbox"  type="text" placeholder="Update Checkbox" class="form-input p-1">
          <%= form_with(url: update_checkbox_concert_template_path(@concert_template)) do |form| %>
            <%= form.hidden_field :checkbox_description, value: "", data: { concert_template_target: "checkboxLinkTemplate#{index}" } %>
            <%= form.hidden_field :index, value: "#{index}" %>
            <div class="d-flex align-items-center">
                <%= form.button 'UPDATE', type: :submit, class: 'button-green ms-2'  %>
                <% end %>
                <%= form_with(url: delete_checkbox_concert_template_path(@concert_template)) do |form| %>
                  <%= form.hidden_field :index, value: "#{index}" %>
                  <%= form.button 'DELETE', type: :submit, class: 'button-delete ms-2'  %>
                <% end %>
            </div>
        </div>
      </div>
    <% end %>
    <div class="d-flex align-items-center">
      <div class="col-lg-6">

      </div>
      <div class="col-lg-6 d-flex align-items-center">
        <input data-concert-template-target="newCheckboxDescription" data-action="keyup->concert-template#newCheckbox"  type="text" placeholder="New Checkbox" class="form-input p-1 mb-2">
        <%= form_with(url: new_checkbox_concert_template_path(@concert_template)) do |form| %>
          <%= form.hidden_field :note_description, value: "", data: { concert_template_target: "newCheckboxTemplate" } %>
          <%= form.button 'NEW', type: :submit, class: 'button-green ms-2 mb-2'  %>
        <% end %>
      </div>
    </div>
</div>

app/views/concert_templates/_hotels.html.erb
<div class="col-12 container-white mt-2">
  <h2>HOTELS (<%= @concert_template.name.upcase %>)</h2>
    <div id="hotel-space">
      <div class="listtogglehotels">
          <% @hotels_data.each_with_index do |hotel_data, index| %>

              <div class="d-flex align-items-center justify-content-between hotel-infos-template">
                <div class="hotels-infos m-2 d-flex align-items-center justify-content-between ">
                  <div>
                    <p class="mb-0"><strong> <%= hotel_data["name"] %></strong></p>
                    <p class="mb-0"> <%= hotel_data["address"] %> </p>
                    <p class="mb-0"> <%= hotel_data["city"] %> (<%= hotel_data["country"] %>)</p>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between hotels-infos-edit">
                  <div class="col-lg-2 ">
                    <input data-concert-template-target="updateHotelName<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateHotelName"  type="text" placeholder="Update Name" class="form-input p-1 mb-1">
                    <input data-concert-template-target="updateHotelAddress<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateHotelAddress"  type="text" placeholder="Update Address" class="form-input p-1 mt-1">
                  </div>
                  <div class="col-lg-2 ">
                    <input data-concert-template-target="updateHotelPostCode<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateHotelPostCode"  type="text" placeholder="Update Postcode" class="form-input p-1 mb-1">
                    <input data-concert-template-target="updateHotelCity<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateHotelCity"  type="text" placeholder="Update City" class="form-input p-1 mt-1">
                  </div>
                  <div class="col-lg-4">
                    <%= form_with(url: update_hotel_concert_template_path(@concert_template)) do |form| %>
                      <div class=" d-flex justify-content-between align-items-center hotel-infos-template-country">
                        <div class="me-2 hotel-infos-template-country-select">
                          <%= form.select :hotel_country, ISO3166::Country.all_translated, { prompt: 'Country' }, class: 'form-input p-1 ms-2 mb-1' %>
                          <%= form.select :standing, [1,2,3,4,5], { prompt: 'Standing' }, class: 'form-input p-1 ms-2 mt-1' %>
                        </div>
                        <%= form.hidden_field :hotel_name, value: "", data: { concert_template_target: "updateHotelNameTemplate#{index}" } %>
                        <%= form.hidden_field :hotel_address, value: "", data: { concert_template_target: "updateHotelAddressTemplate#{index}" } %>
                        <%= form.hidden_field :hotel_postcode, value: "", data: { concert_template_target: "updateHotelPostCodeTemplate#{index}" } %>
                        <%= form.hidden_field :hotel_city, value: "", data: { concert_template_target: "updateHotelCityTemplate#{index}" } %>
                        <%= form.hidden_field :index, value: "#{index}" %>
                        <%= form.button 'UPDATE', type: :submit, class: 'button-green ms-2'  %>
                      </div>
                    <% end %>

                  </div>
                    <%= form_with(url: delete_hotel_concert_template_path(@concert_template)) do |form| %>
                      <%= form.hidden_field :index, value: "#{index}" %>
                      <%= form.button 'DELETE', type: :submit, class: 'button-delete ms-2 '  %>
                    <% end %>

                </div>
              </div>

          <% end %>

            <div class="d-flex align-items-center justify-content-between mt-3 hotel-infos-template-new">
              <div class="col-lg-2">
                <input data-concert-template-target="newHotelName"  data-action="keyup->concert-template#newHotelName"  type="text" placeholder="Name" class="form-input p-1 ">
              </div>
              <div class="col-lg-2">
                <input data-concert-template-target="newHotelAddress"  data-action="keyup->concert-template#newHotelAddress"  type="text" placeholder="Address" class="form-input p-1 ">
              </div>
              <div class="col-lg-1">
                <input data-concert-template-target="newHotelPostCode" data-action="keyup->concert-template#newHotelPostCode"  type="text" placeholder="Postcode" class="form-input p-1 ">
              </div>
              <div class="col-lg-1">
                <input data-concert-template-target="newHotelCity"  data-action="keyup->concert-template#newHotelCity"  type="text" placeholder="City" class="form-input p-1 ">
              </div>
              <div class="col-lg-4">
                <%= form_with(url: new_hotel_concert_template_path(@concert_template)) do |form| %>
                  <div class="d-flex align-items-center justify-content-between hotel-infos-template-new-submit">
                    <div class="col-lg-4">
                      <%= form.select :hotel_country, ISO3166::Country.all_translated, { prompt: 'Country' }, class: 'form-input p-1 ' %>
                    </div>
                    <div class="col-lg-2">
                      <%= form.select :standing, [1,2,3,4,5], { prompt: 'Standing' }, class: 'form-input p-1 ' %>
                    </div>
                    <%= form.hidden_field :hotel_name, value: "", data: { concert_template_target: "newHotelNameTemplate" } %>
                    <%= form.hidden_field :hotel_address, value: "", data: { concert_template_target: "newHotelAddressTemplate" } %>
                    <%= form.hidden_field :hotel_postcode, value: "", data: { concert_template_target: "newHotelPostCodeTemplate" } %>
                    <%= form.hidden_field :hotel_city, value: "", data: { concert_template_target: "newHotelCityTemplate" } %>
                    <div class="col-lg-2 me-3">
                      <%= form.button 'NEW', type: :submit, class: 'button-green '  %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>

      </div>
    </div>
</div>

app/views/concert_templates/_notes.html.erb
<div class="col-12 container-white mt-2">
  <h2>NOTES (<%= @concert_template.name.upcase %>)</h2>
    <div class="mt-3">
      <% if @notes_data.empty? %>
          <p class="m-0"> No notes yet</p>
      <% else %>
        <% @notes_data.each_with_index do |note_data, index| %>
          <div class="list-unstyled d-flex align-items-center concert-note mb-1">
            <div class="d-flex align-items-center  col-lg-6">
              <i class="fa-solid fa-note-sticky me-3"> </i>
              <p class="m-0 me-3"> <%= note_data["description"] %></p>
            </div>
            <div class="col-lg-6 d-flex align-items-center concert-note-edit">
              <input data-concert-template-target="noteDescription<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateNote"  type="text" placeholder="Update Note" class="form-input p-1 ">
              <%= form_with(url: update_notes_concert_template_path(@concert_template)) do |form| %>
                <%= form.hidden_field :note_description, value: "", data: { concert_template_target: "noteLinkTemplate#{index}" } %>
                <%= form.hidden_field :index, value: "", data: { concert_template_target: "noteIndexTemplate#{index}" } %>
                <div class="d-flex align-items-center">
                  <%= form.button 'UPDATE', type: :submit, class: 'button-green ms-2 '  %>
                  <% end %>
                  <%= form_with(url: delete_note_concert_template_path(@concert_template)) do |form| %>
                    <%= form.hidden_field :index, value: "#{index}" %>
                    <%= form.button 'DELETE', type: :submit, class: 'button-delete ms-2 '  %>
                  <% end %>
                </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="d-flex align-items-center">
        <div class="col-lg-6">

        </div>
        <div class="col-lg-6 d-flex align-items-center">
          <input data-concert-template-target="newNoteDescription" data-action="keyup->concert-template#newNote"  type="text" placeholder="New Note" class="form-input p-1 mb-2">
          <%= form_with(url: new_note_concert_template_path(@concert_template)) do |form| %>
            <%= form.hidden_field :note_description, value: "", data: { concert_template_target: "newNoteTemplate" } %>
            <%= form.button 'NEW', type: :submit, class: 'button-green ms-2 mb-2'  %>
          <% end %>
        </div>
      </div>


    </div>

</div>

app/views/concert_templates/_timetable.html.erb
 <div class="col-12 container-white">
  <h2 class="box-shadow-bottom">TIMETABLE (<%= @concert_template.name.upcase %>)</h2>
  <div class="listtoggletimetable">
    <div id="timetable-entries">
      <% @timetable_entries_data.each_with_index do |timetable_entry, index| %>
        <div class="timetable-entry d-flex justify-content-between align-items-center p-2 <%= index.even? ? 'even' : 'odd' %>">
          <div class="timetablehours pe-4">
            <div class="d-flex justify-content-between">
              <p class="mb-0 me-2 timetable-time-size ">
                <% if timetable_entry["hourminute"] %>
                  <%= timetable_entry["hourminute"]&.then { |time| DateTime.parse(time)&.strftime('%H:%M') } %>
                <% else %>
                  empty
                <% end %>
              </p>
              <p class="mb-0 ms-2 timetable-time-size ">
                <% if timetable_entry["hourminuteend"] %>
                  <%= timetable_entry["hourminuteend"]&.then { |time| DateTime.parse(time)&.strftime('%H:%M') }  %>
                <% else %>
                  no entry
                <% end %>
              </p>
            </div>
          </div>
          <div class="timetableinfos ms-4">
            <p class="mb-0"><strong> <%= timetable_entry["information"] %></strong></p>
          </div>

            <input data-concert-template-target="entry<%= index %>" data-index="<%= index %>" data-action="keyup->concert-template#updateEntry"  type="text" placeholder="Update Entry" class="form-input-dark p-1">
              <p class="mb-0 me-2 ms-2 text-dark">from</p>
            <input data-concert-template-target="start<%= index %>" data-index="<%= index %>" data-action="input->concert-template#updateStart"  type="time" placeholder="Update Entry" class="form-input-dark p-1">
              <p class="mb-0 me-2 ms-2  text-dark">to</p>
            <input data-concert-template-target="end<%= index %>" data-index="<%= index %>" data-action="input->concert-template#updateEnd"  type="time" placeholder="Update Entry" class="form-input-dark p-1">
            <%= form_with(url: update_timetable_concert_template_path(@concert_template)) do |form| %>
              <%= form.hidden_field :entry, value: "", data: { concert_template_target: "entryTemplate#{index}" } %>
              <%= form.hidden_field :start, value: "", data: { concert_template_target: "startTemplate#{index}" } %>
              <%= form.hidden_field :end, value: "", data: { concert_template_target: "endTemplate#{index}" } %>
              <%= form.hidden_field :index, value: "#{index}" %>
              <%= form.button 'UPDATE', type: :submit, class: 'button-green ms-2'  %>
            <% end %>
            <%= form_with(url: delete_timetable_concert_template_path(@concert_template)) do |form| %>
              <%= form.hidden_field :index, value: "#{index}" %>
              <%= form.button 'DELETE', type: :submit, class: 'button-delete ms-2 '  %>
            <% end %>

        </div>
      <% end %>
    </div>
  </div>
  <div class=" d-flex justify-content-between align-items-center  mt-4 new-timetable-entry-template">
    <input data-concert-template-target="newentry" data-action="keyup->concert-template#newEntry"  type="text" placeholder="New Entry" class="form-input p-1">
    <p class="mb-0 me-2 ms-2">from</p>
    <input data-concert-template-target="newstart"  data-action="input->concert-template#newStart"  type="time" placeholder="Update Entry" class="form-input p-1">
    <p class="mb-0 me-2 ms-2">to</p>
    <input data-concert-template-target="newend" data-action="input->concert-template#newEnd"  type="time" placeholder="Update Entry" class="form-input p-1">
    <%= form_with(url: new_timetable_concert_template_path(@concert_template)) do |form| %>
      <%= form.hidden_field :entry, value: "", data: { concert_template_target: "newentryTemplate" } %>
      <%= form.hidden_field :start, value: "", data: { concert_template_target: "newstartTemplate" } %>
      <%= form.hidden_field :end, value: "", data: { concert_template_target: "newendTemplate" } %>
      <%= form.button 'NEW', type: :submit, class: 'button-green ms-2'  %>
    <% end %>
  </div>
</div>