config/routes.rb
Rails.application.routes.draw do
  devise_for :tourmen, controllers: {
    sessions: 'tourman/sessions',
    registrations: 'tourman/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get '/pages/search', to: 'pages#search'
  root to: 'pages#home'
  get  'pages/user_dashboard'
  get 'pages/user_concert_dashboard'
  get 'pages/tourman'

  get 'pdf_generator/generate_pdf/:id', to: 'pdf_generator#generate_pdf', as: 'generate_pdf'

  resources :venues
  resources :hotels
  resources :checklist_templates, only: [:new, :create]
  resources :concert_templates, only: [:new, :create, :show] do
    member do
      post 'update_notes', action: :update_notes, as: 'update_notes'
      post 'new_note', action: :new_note, as: 'new_note'
      post 'delete_note', action: :delete_note, as: 'delete_note'
      post 'update_timetable', action: :update_timetable, as: 'update_timetable'
      post 'update_checkbox', action: :update_checkbox, as: 'update_checkbox'
      post 'new_checkbox', action: :new_checkbox, as: 'new_checkbox'
      post 'delete_checkbox', action: :delete_checkbox, as: 'delete_checkbox'
      post 'new_timetable', action: :new_timetable, as: 'new_timetable'
      post 'delete_timetable', action: :delete_timetable, as: 'delete_timetable'
      post 'new_transport', action: :new_transport, as: "new_transport"
      post 'update_transport', action: :update_transport, as: "update_transport"
      post 'delete_transport', action: :delete_transport, as: "delete_transport"
      post 'update_name', action: :update_name, as: "update_name"
      post 'delete_template', action: :delete_template, as: "delete_template"
      post 'update_hotel', action: :update_hotel, as: "update_hotel"
      post 'delete_hotel', action: :delete_hotel, as: "delete_hotel"
      post 'new_hotel', action: :new_hotel, as: "new_hotel"
      post 'create_from_template', action: :create_from_template, as: 'create_from_template'
    end
  end

  resources :tours do
    resources :concerts, except: [:index] do
      resources :timetable_entries, only: [:create, :destroy, :update]
      resources :contacts, only: [:create, :destroy, :update]
      resources :guest_lists, only: [:create, :destroy]
      resources :transports, only: [:create, :destroy, :update] do
        resources :transport_users, only: [:create, :update, :destroy] do
          member do
            delete 'destroy_attachment/:attachment_id', action: :destroy_attachment, as: :destroy_attachment
          end
        end
      end
      resources :crew_user_concerts, only: [:create, :destroy]
      resources :guests, only: [:create, :destroy, :update]
      resources :notes, only: [:create, :destroy, :update]
      resources :checklists, only: [:create, :destroy, :update] do
        collection do
          get 'import'
        end
      end
      delete 'removetimetable/:timetable_entry_id', action: :removetimetable, as: 'removetimetable'
      delete 'remove_contact/:contact_id', action: :remove_contact, as: 'remove_contact'
      patch :remove_venue, on: :member
      patch :remove_hotel, on: :member
      resources :concert_hotels, only: [:create, :destroy] do
        member do
          delete 'remove_user/:user_id', action: :remove_user, as: 'remove_user'
          delete 'remove_guest/:guest_id', action: :remove_guest, as: 'remove_guest'
          post 'add_crew', action: :add_crew, as: 'add_crew'
          post 'add_guest', action: :add_guest, as: 'add_guest'
        end
      end

      get 'roadbook_email', action: :roadbook_email, as: "roadbook_email"

    end
  end

  resources :crews do
    member do
      post 'assign_users'
      put 'assign_users_role'
      put 'update_role_in_crew_member/:user_id', to: 'crews#update_role_in_crew_member', as: :update_role_in_crew_member
      delete 'unassign_user/:user_id', action: :unassign_user, as: :unassign_user
    end
  end

end

app/controllers/sidebar_controller.rb
class SidebarController < ApplicationController

  def tourman_sidebar
    @tours = policy_scope(Tour)
  end
end

app/views/sidebar/_tourman_sidebar.html.erb
<div class="side-bar-container">
  <div class="side-bar-home ">

       <%= image_tag "logo.png", class: "sidebar-logo" %>


  </div>
  <div class="side-bar-menu">
    <strong>
      <div class="mb-3 d-flex align-items-center justify-content-between"> <span class="text-white">TOURS</span>  <%= link_to "+", new_tour_path, class:" ms-2 button-plus" %></div>
    </strong>
    <div class="side-bar-tour mb-3">
      <% @tours.each do |tour| %>
        <li class="list-unstyled">
          <%= link_to tour_path(tour) do %>
            <div class="side-bar-tour-card col-5">
              <div class="side-bar-tour-card-img">
                <%= image_tag(tour.picture) if tour.picture.attached? %>
                <% unless tour.picture.attached? %>
                  <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "avatar" %>
                <% end %>
              </div>
              <div class="side-bar-tour-card-content d-flex align-items-center">
                <span><h2><%= tour.artist.upcase %></h2> <h3><%= tour.title.upcase%></h3></span>
              </div>

            </div>
          <% end %>
        </li>
      <% end %>
    </div>
    <strong>
      <div class="mb-3 d-flex align-items-center justify-content-between">
        <div id="templates-sidebar-screens">
          <span class="text-white">TEMPLATES</span>
        </div>
        <div id="templates-sidebar-phones">
          <span class="text-white"><i class="fa-solid fa-paintbrush"></i></span>
        </div>
        <%= link_to "+", new_concert_template_path, class:" ms-2 button-plus" %>
      </div>
    </strong>
    <div class="templates_list mb-3">
      <% @concert_templates.each do |concert_template| %>
        <li class="list-unstyled ">
          <%= link_to concert_template_path(concert_template) do %>
              <div class="templates_items">
                <span><p class="m-0"><%= concert_template.name.upcase %></p> </span>
              </div>
          <% end %>
        </li>
      <% end %>
    </div>
    <strong>
      <div class="mb-3 d-flex align-items-center justify-content-between">
        <%= link_to hotels_path do %>
          <span class="text-white">HOTELS</span>
        <% end %>
      </div>
    </strong>
    <strong>
      <div class="mb-3 d-flex align-items-center justify-content-between">
        <%= link_to venues_path do %>
          <span class="text-white">VENUES</span> </div>
        <% end %>
    </strong>
  </div>
</div>

app/views/sidebar/_user_sidebar.html.erb
<div class="side-bar-container">
  <div class="side-bar-home ">
    <strong>
      <span>SIMPLER TOUR</span>
    </strong>
  </div>
  <div class="side-bar-menu">
    <strong>
      <div class="mb-3 d-flex align-items-center justify-content-between"> <span class="text-white">TOURS</span>  </div>
    </strong>
    <div class="side-bar-tour mb-3">
      <% @tours.each do |tour| %>

        <li class="list-unstyled">

            <div class="side-bar-tour-card col-5">
              <div class="side-bar-tour-card-img">
                <%= image_tag(tour.picture) if tour.picture.attached? %>
                <% unless tour.picture.attached? %>
                  <%= image_tag "https://static.vecteezy.com/ti/gratis-vector/p3/7319933-black-avatar-person-icons-user-profile-icon-vector.jpg", class: "avatar" %>
                <% end %>
              </div>
              <div class="side-bar-tour-card-content d-flex align-items-center">
                <span><h2><%= tour.artist.upcase %></h2> <h3><%= tour.title.upcase%></h3></span>
              </div>

            </div>

        </li>
      <% end %>
    </div>
  </div>
</div>