config/routes.rb
Rails.application.routes.draw do
  devise_for :tourmen, controllers: {
    sessions: 'tourman/sessions',
    registrations: 'tourman/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get '/pages/search', to: 'pages#search'
  root to: 'pages#home'
  get  'pages/user_dashboard'
  get 'pages/user_concert_dashboard'
  get 'pages/tourman'

  get 'pdf_generator/generate_pdf/:id', to: 'pdf_generator#generate_pdf', as: 'generate_pdf'

  resources :venues
  resources :hotels
  resources :checklist_templates, only: [:new, :create]
  resources :concert_templates, only: [:new, :create, :show] do
    member do
      post 'update_notes', action: :update_notes, as: 'update_notes'
      post 'new_note', action: :new_note, as: 'new_note'
      post 'delete_note', action: :delete_note, as: 'delete_note'
      post 'update_timetable', action: :update_timetable, as: 'update_timetable'
      post 'update_checkbox', action: :update_checkbox, as: 'update_checkbox'
      post 'new_checkbox', action: :new_checkbox, as: 'new_checkbox'
      post 'delete_checkbox', action: :delete_checkbox, as: 'delete_checkbox'
      post 'new_timetable', action: :new_timetable, as: 'new_timetable'
      post 'delete_timetable', action: :delete_timetable, as: 'delete_timetable'
      post 'new_transport', action: :new_transport, as: "new_transport"
      post 'update_transport', action: :update_transport, as: "update_transport"
      post 'delete_transport', action: :delete_transport, as: "delete_transport"
      post 'update_name', action: :update_name, as: "update_name"
      post 'delete_template', action: :delete_template, as: "delete_template"
      post 'update_hotel', action: :update_hotel, as: "update_hotel"
      post 'delete_hotel', action: :delete_hotel, as: "delete_hotel"
      post 'new_hotel', action: :new_hotel, as: "new_hotel"
      post 'create_from_template', action: :create_from_template, as: 'create_from_template'
    end
  end

  resources :tours do
    resources :concerts, except: [:index] do
      resources :timetable_entries, only: [:create, :destroy, :update]
      resources :contacts, only: [:create, :destroy, :update]
      resources :guest_lists, only: [:create, :destroy]
      resources :transports, only: [:create, :destroy, :update] do
        resources :transport_users, only: [:create, :update, :destroy] do
          member do
            delete 'destroy_attachment/:attachment_id', action: :destroy_attachment, as: :destroy_attachment
          end
        end
      end
      resources :crew_user_concerts, only: [:create, :destroy]
      resources :guests, only: [:create, :destroy, :update]
      resources :notes, only: [:create, :destroy, :update]
      resources :checklists, only: [:create, :destroy, :update] do
        collection do
          get 'import'
        end
      end
      delete 'removetimetable/:timetable_entry_id', action: :removetimetable, as: 'removetimetable'
      delete 'remove_contact/:contact_id', action: :remove_contact, as: 'remove_contact'
      patch :remove_venue, on: :member
      patch :remove_hotel, on: :member
      resources :concert_hotels, only: [:create, :destroy] do
        member do
          delete 'remove_user/:user_id', action: :remove_user, as: 'remove_user'
          delete 'remove_guest/:guest_id', action: :remove_guest, as: 'remove_guest'
          post 'add_crew', action: :add_crew, as: 'add_crew'
          post 'add_guest', action: :add_guest, as: 'add_guest'
        end
      end

      get 'roadbook_email', action: :roadbook_email, as: "roadbook_email"

    end
  end

  resources :crews do
    member do
      post 'assign_users'
      put 'assign_users_role'
      put 'update_role_in_crew_member/:user_id', to: 'crews#update_role_in_crew_member', as: :update_role_in_crew_member
      delete 'unassign_user/:user_id', action: :unassign_user, as: :unassign_user
    end
  end

end

app/models/concert.rb
class Concert < ApplicationRecord

  STATUS_MAPPING = {
    0 => "Not Started",
    1 => "On Going",
    2 => "All Good",
    3 => "Past"
  }

  STATUS_CHOICES = STATUS_MAPPING.keys


  belongs_to :tour
  belongs_to :venue, optional: true
  belongs_to :hotel, optional: true
  before_destroy :remove_associations
  has_many :concert_hotels, dependent: :destroy
  has_many :hotels, through: :concert_hotels
  has_many :transports, dependent: :destroy
  has_many :timetable_entries, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :checklists, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :guest_lists, dependent: :destroy
  has_many :crew_user_concerts, dependent: :destroy
  validates :status, presence: true, inclusion: { in: STATUS_CHOICES }

  def status_name
    STATUS_MAPPING[status]
  end

  def calculate_status
    if date < Date.today
      return 3 # Past
    elsif checklists.empty?(&:status)
      return 0 # Not started
    elsif checklists.all?(&:status)
      return 2 # All Good
    elsif checklists.any?(&:status)
      return 1 # On Going
    elsif checklists.none?(&:status)
      return 0 # Not started
    end
  end

  private

  def remove_associations
    checklists.each do |checklist|
      checklist.update(concert_id: nil)
      checklist.destroy
    end
    timetable_entries.each do |timetable_entry|
      timetable_entry.update(concert_id: nil)
      timetable_entry.destroy
    end
    transports.each do |transport|
      transport.update(concert_id: nil)
      transport.destroy
    end
    notes.each do |note|
      note.update(concert_id: nil)
      note.destroy
    end
    concert_hotels.each do |concert_hotel|
      concert_hotel.update(concert_id: nil)
      concert_hotel.destroy
    end
    contacts.each do |contact|
      contact.update(concert_id: nil)
      contact.destroy
    end
    guest_lists.each do |guest_list|
      guest_list.update(concert_id: nil)
      guest_list.destroy
    end
    crew_user_concerts.each do |crew_user_concert|
      crew_user_concert.update(concert_id: nil)
      crew_user_concert.destroy
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  def new
    @tour = Tour.find(params[:tour_id])
    @concert = @tour.concerts.build
  end

  def show
    @concert_templates = ConcertTemplate.where(tourman_id: current_tourman.id)
    @tours = Tour.where(tourman_id: current_tourman.id)
    @phoneprefix = ISO3166::Country.all.map { |country| "#{country.country_code}" }
    @phoneprefixsorted = @phoneprefix.uniq.sort_by(&:to_i).map {|c| "+#{c}"}
    @contact = Contact.new
    @guest = Guest.new
    @note = Note.new
    @checklist = Checklist.new
    @concert_template = ConcertTemplate.new
    @transport = Transport.new
    @transport_user = TransportUser.new
    @hotel = Hotel.new
    @concert = Concert.find(params[:tour_id])
    @contacts = @concert.contacts
    @checklists = @concert.checklists
    @notes = @concert.notes
    @guests = @concert.guests
    @tour = Tour.find(params[:id])
    @crew = @tour.crew
    @guest_lists =  @concert.guest_lists
    @guest_list =  GuestList.new
    @timeentry = TimetableEntry.new
    @timetable_entries = TimetableEntry.where(concert_id: @concert).order(hourminute: :asc)
    status = @concert.calculate_status
    @status_text = Concert::STATUS_MAPPING[status]
    @concert.status = status
    @concert.save
    @crew_users = @crew.crew_users
    @crew_user_concert = CrewUserConcert.new
    @users_on_this_concert = []
    @crew_user_concerts = @concert.crew_user_concerts
    @crew_user_concerts.each do |crew_user_concert|
      @users_on_this_concert << crew_user_concert.crew_user.user
    end
    @checklist_template = ChecklistTemplate.new
    @checklist_templates = ChecklistTemplate.where(tourman_id: current_tourman.id)
    @hotel_geocoders = []
    @venue_geocoders = []
    if @concert.venue_id.present?
      @venue = Venue.find(@concert.venue_id)
      @venue_geocoders <<  @venue
    end
    if @concert.concert_hotels.present?
      hotel_ids_array = @concert.concert_hotels.pluck(:hotel_id)
      hotel_ids_array.each do |hotel|
        @hotel_geocoders <<  Hotel.find(hotel)
      end
    end
    @venue_markers =  @venue_geocoders.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {location: location}),
        marker_html: render_to_string(partial: "venue_marker")
      }
    end
    @hotel_markers =  @hotel_geocoders.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {location: location}),
        marker_html: render_to_string(partial: "hotel_marker")
      }
    end
    authorize @concert
  end

  def create
    @tour = Tour.find(params[:tour_id])
    @concert = @tour.concerts.build(concert_params)
    authorize @concert
    @concert.venue = nil
    if @concert.save
      redirect_to tour_path(@tour), notice: 'Concert was successfully created.'
    else
      redirect_to tour_path(@tour), notice: 'Could not add a new show something went wrong'
    end
  end

  def edit
    @tour = Tour.find(params[:tour_id])
    @concert = @tour.concerts.find(params[:id])
    authorize @concert
  end

  def update
    @tour = Tour.find(params[:tour_id])
    @concert = @tour.concerts.find(params[:id])
    authorize @concert
    if @concert.update(concert_params)
      redirect_to tour_concert_path(@concert), notice: 'Concert was successfully updated.'
    else
      render :show
    end
  end

  def destroy
    @tour = Tour.find(params[:tour_id])
    @concert = @tour.concerts.find(params[:id])
    authorize @concert
    @concert.destroy
    redirect_to tour_path(@tour), notice: 'Concert was successfully deleted.'
  end

  def remove_venue
    @tour = Tour.find(params[:id].to_i)
    @concert = Concert.find(params[:tour_id])
    @concert.update(venue_id: nil)
    authorize @concert
    redirect_to tour_concert_path(@tour, @concert), notice: 'Venue Removed'
  end

  def removetimetable
    @timetable_entry = TimetableEntry.find(params[:timetable_entry_id].to_i)
    @concert = Concert.find(params[:concert_id].to_i)
    @tour = Tour.find(params[:tour_id].to_i)
    authorize @concert
    @timetable_entry.destroy
    redirect_to tour_concert_path(@tour, @concert), notice: 'Timetable updated'
  end

  def remove_contact
    @contact = Contact.find(params[:contact_id].to_i)
    @concert = Concert.find(params[:concert_id].to_i)
    @tour = Tour.find(params[:tour_id].to_i)
    authorize @concert
    @contact.destroy
    redirect_to tour_concert_path(@tour, @concert), notice: 'Contact Delete'
  end

  def roadbook_email
    @concert = Concert.find(params[:tour_id].to_i)
    authorize @concert
    @tour = Tour.find(params[:concert_id].to_i)
    @crew = @tour.crew
    @crew_users = @crew.users
    @crew_users.each do |user|
      RoadbookMailer.roadbook_email(user).deliver_now
    end
    redirect_to tour_concert_path(@concert, @tour), notice: 'Mails sent'
  end

  private

  def concert_params
    params.require(:concert).permit(:date, :location, :name, :venue_id, hotel_ids: [])
  end
end

app/views/concerts/_checkboxes.html.erb
 <div class="col-12 container-white mt-2">
        <h2>CHECKBOXES</h2>
          <%= render partial: 'checklist_form', locals: { tour: @tour, concert: @concert, checklist: @checklist, checklist_template: @checklist_template} %>
          <% if @checklists.present? %>
            <div class="listtogglecheckboxes ">
              <% @checklists.each_with_index do |checklist, index| %>
                <div class="checklist-item">
                  <div class="d-flex align-items-center justify-content-between">
                    <div class="status me-1 d-flex align-items-center" data-controller="checklist">
                        <%= simple_form_for [@tour, @concert, checklist], data: {class: "m-0"} do |f| %>
                          <div class="d-flex align-items-center form-checklist-div">
                            <%= f.input :status, label: "#{checklist.description}", as: :boolean, input_html: { data: { action: 'change->checklist#updateStatus', checklist_target: 'checkbox', index: "#{index}", id: "#{checklist.id}", tour: "#{@tour.id}", concert: "#{@concert.id}" } }%>
                            <%= f.submit "UPDATE STATUS", class:"d-none" %>
                          </div>
                        <% end %>
                    </div>
                    <%= link_to raw('<i class="fa-solid fa-minus open-plus-icon"></i>'), tour_concert_checklist_path(@tour, @concert, checklist), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>

</div>

app/views/concerts/_contact_form.html.erb
  <span class="close-contert-modal " data-action="click->concert#closeModalContact"><i class="fas fa-times black-icon"></i></span>
  <div class="mt-2">
    <%= simple_form_for [@tour, @concert, @contact] do |f| %>
      <%= f.input :full_name, label: false, placeholder: "Full name", input_html: {class: 'form-input' }%>
      <%= f.input :role, label: false, placeholder: "Role(s)",input_html: {class: 'form-input' }%>
      <%= f.input :email,label: false, placeholder: "Email", input_html: {class: 'form-input' }%>
      <div class="d-flex justify-content-around">
        <%= f.input :country_code, collection: @phoneprefixsorted,  label: false, prompt: "+", input_html: { class: 'form-input' } %>
        <%= f.input :phone_number, label: false, input_html: {class: 'form-input' }, placeholder: "Phone Number"%>
      </div>
      <div class="text-center">
        <%= f.submit "NEW CONTACT", class:"button-green" %>
      </div>
    <% end %>
  </div>

app/views/concerts/_contacts.html.erb
 <div class="w-100 ms-1 container-white contacts-box ">
          <div class="d-flex align-items-center justify-content-between mb-3">
            <h2 class="mb-0">CONTACTS</h2>
          </div>
          <div class="listtogglecontact">
            <% if !@contacts.empty?%>
              <% @contacts.each do |contact| %>
                <div class="contacts-concert d-flex justify-content-between align-items-center">
                  <div class="w-100">
                    <p class="m-0"><strong><%= contact.role %>:</strong> <%= contact.full_name %> </p>
                    <p class="m-0"><em><a href="mailto:<%= contact.email %>"><%= contact.email %></a></em></p>
                    <p class="m-0"> <em><%= contact.full_number %></em>  </p>
                  </div>
                  <div class="">
                    <%= link_to raw('<i class="fa-solid fa-minus open-plus-icon me-3"></i>'), tour_concert_remove_contact_path(@tour, @concert, contact),   data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>


          <div class="text-center mt-3">
            <a href="#" data-action="click->concert#openModalContact" class="button-plus" ><strong>+</strong></a>
          </div>


          <div class="modal-new-contact" data-concert-target="modalcontact">
            <div class="modal-new-contact-content">
              <%= render partial: 'contact_form', locals: { tour: @tour, concert: @concert, contact: @contact, phoneprefixsorted: @phoneprefixsorted } %>
            </div>
          </div>
        </div>

app/views/concerts/_hotel_marker.html.erb
<%= image_tag "hotel.png", height: 40, width: 40, alt: "Logo" %>

app/views/concerts/_info_window.html.erb
<div class="map-card">
  <h2><%= location.name %></h2>
</div>
<div class="circle-map-card"></div>

app/views/concerts/_new_hotel_form.html.erb
<%= simple_form_for(@hotel) do |f| %>

    <%= f.input :name,
        label: false,
        placeholder: "Hotel Name",
        input_html: { class: 'form-input' }  %>

    <%= f.input :address,
        label: false,
        placeholder: "Address",
        input_html: { class: 'form-input' } %>
    <div class="d-flex justify-content-between">
      <%= f.input :postcode,
          label: false,
          placeholder: "Post Code",
          input_html: { class: 'form-input' } %>

      <%= f.input :city,
          label: false,
          placeholder: "City",
          input_html: { class: 'form-input' }
      %>
      <%= hidden_field_tag :concert, @concert.id %>
      <%= hidden_field_tag :tour, @tour.id %>

      <%= f.input :country,
          label: false,
          prompt: "Select a country",
          input_html: { class: 'form-input' }  %>
    </div>
    <div class="d-flex justify-content-between">
      <%= f.input :standing,
          label: false,
          placeholder: "Standing",
          input_html: { class: 'form-input' } %>

      <%= f.submit "NEW HOTEL", class:"button-green mb-3" %>
    </div>
  <% end %>

app/views/concerts/_notes.html.erb
  <div class="col-12 container-white mt-2">
        <h2>NOTES</h2>
          <%= render partial: 'note_form', locals: { tour: @tour, concert: @concert, note: @note } %>
          <div class="mt-3">
            <% if @notes.empty? %>
               <p class="m-0"> No notes yet</p>
            <% else %>
              <% @notes.each do |note| %>

                <li class="list-unstyled d-flex align-items-center  concert-note-phones">
                  <i class="fa-solid fa-note-sticky me-3"> </i>
                  <p class="m-0 me-3"> <%= note.description %></p>
                  <%= link_to raw('<i class="fa-solid fa-minus open-plus-icon"></i>'), tour_concert_note_path(@tour, @concert, note), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
                </li>
              <% end %>
            <% end %>

          </div>

      </div>

app/views/concerts/_timetable.html.erb
 <div class="col-12 container-white">
          <h2 class="box-shadow-bottom">TIMETABLE</h2>
          <div class="listtoggletimetable">
            <div id="timetable-entries">
              <% @timetable_entries.each_with_index do |timetable_entry, index| %>
                <div class="timetable-entry timetable-entry-phones d-flex justify-content-between p-2 <%= index.even? ? 'even' : 'odd' %>">
                  <div class="timetablehours timetablehours-phones d-flex align-items-center ps-2 pe-2">
                    <div class="d-flex justify-content-between">
                      <div class="timetable-time-size text-center"><p class="mb-0 me-2"><%= timetable_entry.hourminute&.strftime('%H:%M')%></p></div>
                      <div class="timetable-time-size text-center">
                        <% if timetable_entry.hourminuteend.nil? %>
                          <p class="mb-0 ms-2"></p>
                        <% else %>
                          <p class="mb-0 ms-2"><%= timetable_entry.hourminuteend&.strftime('%H:%M') %></p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="timetableinfos  d-flex align-items-center ms-4">
                    <p class="mb-0"><strong> <%= timetable_entry.information %></strong></p>
                  </div>
                  <div class="remove-timetable-entry">
                    <%= link_to raw('<i class="fa-solid fa-minus open-plus-icon me-3"></i>'), tour_concert_removetimetable_path(@tour, @concert, timetable_entry),  data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="text-center mt-3">
            <strong><a href="#" data-action="click->concert#openModal" class="button-plus" >+</a></strong>
          </div>

          <div class="modal-new-timetable" data-concert-target="modal">

            <div class="modal-new-timetable-content">
              <span class="close-contert-modal" data-action="click->concert#closeModal"><i class="fas fa-times black-icon"></i></span>
              <%= form_for [@tour, @concert, @timeentry] do |f| %>
              <div class=" mb-3">
                <div class="d-flex mb-2">
                  <div class="from-to"><p class="m-0 me-2"><strong>From: </strong></p></div>
                  <%= f.time_field :hourminute, class: 'hour_pickr form-input-hour ' %>
                </div>
                <div class="d-flex">
                  <div class="from-to"><p class="m-0 me-2"><strong>To:     </strong></p></div>
                  <%= f.time_field :hourminuteend, class: 'hour_pickr form-input-hour ' %>
                </div>
              </div>

              <div class="mb-3">
                <%= f.text_field :information, class: 'hour_pickr form-input-address ', placeholder:"Event" %>
              </div>
              <div class="mb-0 text-center">
                <%= f.submit "NEW ENTRY", data: { action: "submit->concert#closeModal"}, class:"button-green" %>
              </div>
              <% end %>
            </div>
          </div>
      </div>

app/views/concerts/_transport.html.erb
<div class="col-12 container-white mb-2">
  <h2>TRANSPORTS</h2>
  <% if !@concert.transports.present? %>
    <p>No transports added yet</p>
  <% else %>
    <% @concert.transports.each_with_index do |transport, index|%>
      <%= render partial: 'transport_ride', locals: { tour: @tour, concert: @concert, transport: transport, index: index } %>
    <% end %>
  <% end %>

  <div class="text-center mt-3">
    <a href="#" data-action="click->concert#openModalTransport" class="button-plus" ><strong>+</strong></a>
  </div>

  <div class="modal-new-transport" data-concert-target="modaltransport">
    <div class="modal-new-transport-content">
      <%= render partial: 'transport_form', locals: { tour: @tour, concert: @concert, transport: @transport } %>
    </div>
  </div>
</div>

app/views/concerts/_transport_form.html.erb
<span class="close-contert-modal " data-action="click->concert#closeModalTransport"><i class="fas fa-times black-icon"></i></span>
  <div class="mt-2">
    <%= simple_form_for [@tour, @concert, @transport] do |f| %>
      <%= f.input :way_of_transport, collection: Transport::WAY_OF_TRANSPORT_OPTIONS, prompt: 'Select Way of Transport', label: false, placeholder: "Transport mode", input_html: {class: 'form-input' }%>
      <div class="d-flex justify-content-between">
        <div class="col-4">
          <%= f.input :time_of_depart, as: :time, label: false, placeholder: "Time of departure", input_html: {class: 'form-input' }%>
        </div>
        <div class="col-7">
          <%= f.input :place_of_depart, label: false, placeholder: "Place of departure", input_html: {class: 'form-input' }%>
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <div class="col-4">
          <%= f.input :time_of_arrival,  as: :time, label: false, placeholder: "Time of arrival", input_html: {class: 'form-input' }%>
        </div>
        <div class="col-7">
          <%= f.input :place_of_arrival, label: false, placeholder: "Place of arrival", input_html: {class: 'form-input' }%>
        </div>
      </div>
      <div class="text-center">
        <%= f.submit "NEW TRANSPORT", class:"button-green" %>
      </div>
    <% end %>
  </div>

app/views/concerts/_venue.html.erb
<div class="col-12 container-white mb-2">
  <h2>VENUE</h2>
  <div id="venue-space">
    <% if @concert.venue %>
      <ul class="list-unstyled">
        <li><p><strong>Address:</strong> <%= @concert.venue.address %></p></li>
        <li><p><strong>City:</strong> <%= @concert.venue.city %> (<%= @concert.venue.country %>) </p></li>
        <li><p><strong>Capacity:</strong> <%= @concert.venue.capacity %> </p></li>
      </ul>
      <div class="d-flex">
        <div class="dropdown me-2">
          <button class="button-green dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            ACTIONS
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><%= button_to 'REMOVE VENUE', remove_venue_tour_concert_path(@concert), method: :patch, remote: true, class: 'dropdown-item' %></li>
            <li><%= link_to 'UPDATE VENUE INFOS', edit_venue_path(@concert.venue.id),  remote: true, class: 'dropdown-item ' %></li>
          </ul>
        </div>
        <a href="#" data-action="click->concert#openModalVenueAttachments" class="button-green">ATTACHMENTS</a>
        <div class="modal-venue-attachments" data-concert-target="venueattachments">
          <div class="modal-venue-attachments-content">
            <%= render partial: 'venue_attachments', locals: { concert: @concert} %>
          </div>
        </div>
      </div>
    <% else %>
      <p><%= link_to 'NEW VENUE', new_venue_path(@concert), class: 'button-green'%></p>
      <div class="d-flex align-items-center">
      <p class="mb-0 me-3">Or:</p>
            <%= form_with(model: [@tour, @concert]) do |form| %>
            <div class="d-flex">
              <%= form.collection_select(:venue_id, Venue.where(tourman_id: current_tourman.id), :id, :name, { prompt: 'Search in DB' }, class:"form-input me-2") %>
              <%= form.submit 'Assign Venue', class:"button-green" %>
            </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/concerts/_venue_attachments.html.erb
<span class="close-contert-modal " data-action="click->concert#closeModalVenueAttachments"><i class="fas fa-times black-icon"></i></span>
<% @concert.venue.files.each do |file| %>
  <p class="list-unstyled attachment-file mb-2"><%= link_to file.filename, rails_blob_path(file, disposition: 'attachment'), target: '_blank' %></p>
<% end %>

app/views/concerts/edit.html.erb
<%= form_for [@tour, @concert] do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Update Concert" %>
<% end %>

app/views/concerts/new.html.erb
<%= form_for [@tour, @concert] do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Create Concert" %>
<% end %>